### PR TITLE
feat: pass team info to BlocksTable

### PR DESCRIPTION
**Pull request by wackerow**
Enables team details within "best metric" tooltip

image

- Adds additional db query in app/page.tsx
- Adds optional `team` field to `Proof` type
- Team info matched by `user_id` to proof before passing to client-side BlockTable component
- Truncates fallback uuid values
- Shows truncated machine_id for machine still

### CODE REVIEW

**Comment by wackerow** [comment]
@pettinarip Curious your thoughts here on best way to get this team data into the table... Each proof has one team so I took the approach of including that in the Proof type, but not necessarily convinced it's the best way.

**Comment by wackerow** [comment]
And similarly, we need to also fetch the machine name from the proving machines table still

**Comment by pettinarip** [comment]
@wackerow we could get the machine info from the blocks query...but the team, it doesn't seem to be an easy solution using the supabase query lib. Probably a lack of db normalisation, will think a bit more about this but in the meantime, I think is ok to do what you did.

Another option that I was thinking about was about doing this an async query. We don't really need this team/machine data immediately. We could fetch the data when users hover them. Not sure, just an idea.

**Review by pettinarip — APPROVED** [review]
Looks great! gj @wackerow

**Pull request merged**
